export const CasualQuestions: string[] = [
  "Kalau hari ini bebas seharian, kamu mau ngapain?",
  "Minuman favorit kamu kalau lagi capek?",
  "Lebih pilih pantai atau gunung?",
  "Lagu apa yang sering kamu putar akhir-akhir ini?",
  "Kalau bisa langsung liburan sekarang, mau ke mana?",
  "Film yang paling sering kamu tonton ulang?",
  "Kebiasaan kecil kamu yang orang jarang tahu?",
  "Sarapan favorit kamu?",
  "Kalau lagi bad mood, biasanya kamu ngapain?",
  "Lebih suka chat atau telepon?",
  "Makanan yang selalu bikin kamu bahagia?",
  "Tempat nongkrong favorit kamu?",
  "Kalau hujan deras, kamu lebih suka di rumah atau keluar?",
  "Hobi yang pengen kamu tekuni tapi belum kesampaian?",
  "Aplikasi yang paling sering kamu buka?",
  "Hal random yang bikin kamu ketawa?",
  "Kamu tipe bangun pagi atau begadang?",
  "Kalau nonton film, lebih suka sendiri atau bareng?",
  "Cemilan favorit pas malam hari?",
  "Musik galau atau musik semangat?",
  "Hal kecil yang bikin hari kamu jadi lebih baik?",
  "Kalau weekend ideal menurut kamu seperti apa?",
  "Mending kopi atau teh?",
  "Kebiasaan aneh tapi nyaman buat kamu?",
  "Kalau lagi capek kerja, hal pertama yang kamu cari apa?",
  "Lebih suka suasana ramai atau sepi?",
  "Kalau masak, menu paling jago apa?",
  "Emoji yang paling sering kamu pakai?",
  "Kalau punya hewan peliharaan, pengennya apa?",
  "Cuaca favorit kamu?",
  "Kalau lagi nunggu sesuatu, biasanya ngapain?",
  "Hal sederhana yang sering kamu syukuri?",
  "Kalau disuruh describe diri kamu dengan 3 kata?",
  "Lebih suka nonton series atau film?",
  "Momen kecil yang sering kamu rindukan?",
  "Kalau lagi bete, kamu pengen ditemani atau sendiri?",
  "Makanan yang nggak pernah bosen kamu makan?",
  "Kalau libur panjang, lebih pilih istirahat atau jalan?",
  "Hal random yang bikin kamu langsung ingat aku?",
  "Waktu favorit dalam sehari?",
  "Kalau disuruh tukar pekerjaan sehari, mau jadi apa?",
  "Game atau permainan favorit kamu?",
  "Lebih suka foto atau video?",
  "Hal kecil yang bikin kamu merasa tenang?",
  "Kalau malam nggak bisa tidur, biasanya ngapain?",
  "Kalau mood lagi bagus, kelihatan dari apa?",
  "Makanan manis atau asin?",
  "Tempat yang bikin kamu merasa aman?",
  "Hal kecil yang sering bikin kamu tersenyum sendiri?",
  "Kalau lagi kangen seseorang, biasanya kamu ngapain?",
  "Kalau disuruh pilih satu lagu buat hari ini, lagu apa?",
  "Hal paling random yang kamu lakukan minggu ini?",
  "Kalau lagi sendirian di rumah, ngapain biasanya?",
  "Hal kecil yang bikin kamu ilfeel?",
  "Kalau nonton YouTube, topik favorit kamu apa?",
  "Lebih suka jalan pagi atau malam?",
  "Kalau lagi capek, pengen ditemani atau didiemin?",
  "Makanan favorit waktu kecil?",
  "Kalau disuruh liburan dadakan, siap nggak?",
  "Hal kecil yang bikin kamu merasa produktif?",
  "Kalau lagi bete, kamu lebih suka ngomel atau diam?",
  "Minuman yang paling sering kamu beli?",
  "Kalau hujan, kamu tipe rebahan atau tidur?",
  "Hal random yang sering kamu pikirin?",
  "Lebih suka kado atau quality time?",
  "Kalau lagi seneng, biasanya kamu ngapain?",
  "Hal kecil yang bikin kamu merasa lucu sendiri?",
  "Kalau disuruh masak buat aku, kamu masak apa?",
  "Hal sederhana yang bikin kamu merasa dicari?",
  "Kalau lagi kosong pikiran, kamu mikir apa?",
  "Lebih suka suasana cafe atau rumah?",
  "Kalau lagi capek mental, kamu ngapain?",
  "Hal kecil yang bikin kamu nyaman sama seseorang?",
  "Kalau lagi males, cara kamu balikin mood gimana?",
  "Momen kecil yang bikin kamu merasa hidup?",
  "Kalau lagi diem lama, kamu mikir apa?",
  "Hal kecil yang bikin kamu merasa diperhatiin?",
  "Kalau disuruh jujur, kamu tipe posesif nggak?",
  "Hal random yang bikin kamu ketawa sendiri di HP?",
  "Kalau lagi nunggu balasan chat, ngapain biasanya?",
  "Hal kecil yang bikin kamu senyum tanpa sadar?",
  "Kalau disuruh pilih satu hal buat diulang, apa?",
  "Kalau hari ini mood kamu warna, warnanya apa?",
  "Hal kecil yang bikin kamu merasa diterima?",
  "Kalau lagi santai, kamu lebih suka ngapain?",
  "Kalau lagi hujan dan dingin, makanan apa yang paling kamu cari?",
  "Hal kecil apa yang bikin kamu langsung bad mood?",
  "Kalau disuruh libur tanpa HP sehari, sanggup nggak?",
  "Minuman favorit kamu kalau lagi panas banget?",
  "Kalau lagi capek banget, kamu lebih pilih tidur atau scroll HP?",
  "Hal sepele apa yang bikin kamu ngerasa diperhatiin?",
  "Kalau lagi diem, kamu beneran kosong atau banyak mikir?",
  "Kalau disuruh pilih: pagi cerah atau malam tenang?",
  "Makanan yang kamu suka tapi orang lain sering nggak suka?",
  "Kalau lagi seneng, kamu tipe cerita atau simpan sendiri?",
  "Hal kecil apa yang bikin kamu betah di satu tempat?",
  "Kalau lagi males ngomong, biasanya kenapa?",
  "Kegiatan santai favorit kamu tanpa gadget?",
  "Kalau lagi jenuh, kamu pengen diajak ngapain?",
  "Hal sederhana yang bikin kamu ngerasa ditemani?",
];

export const DeepQuestions: string[] = [
  "Apa arti hubungan yang sehat menurut kamu?",
  "Hal apa yang paling kamu takuti dalam hubungan?",
  "Apa luka emosional yang masih kamu bawa sampai sekarang?",
  "Menurut kamu, cinta itu pilihan atau perasaan?",
  "Hal apa yang paling sulit kamu ungkapkan ke orang lain?",
  "Kapan terakhir kali kamu merasa sangat rapuh?",
  "Apa yang membuat kamu merasa benar-benar dicintai?",
  "Menurut kamu, apa tanggung jawab terbesar dalam hubungan?",
  "Hal apa yang paling kamu hargai dari pasangan?",
  "Apa batasan yang penting buat kamu dalam hubungan?",
  "Apa ketakutan terbesar kamu tentang masa depan?",
  "Kapan kamu merasa paling bangga pada diri sendiri?",
  "Apa definisi bahagia versi kamu?",
  "Hal apa yang paling sulit kamu maafkan?",
  "Apa yang biasanya kamu pendam sendiri?",
  "Menurut kamu, apa arti komitmen?",
  "Hal apa yang bisa membuat kamu menjauh dari seseorang?",
  "Apa yang paling kamu butuhkan saat sedang down?",
  "Bagaimana cara kamu menghadapi konflik?",
  "Apa pengalaman hidup yang paling membentuk kamu?",
  "Apa mimpi terbesar kamu yang jarang kamu ceritakan?",
  "Hal apa yang bikin kamu merasa tidak cukup?",
  "Menurut kamu, pasangan ideal itu seperti apa?",
  "Apa arti rumah bagi kamu?",
  "Hal apa yang bikin kamu merasa aman secara emosional?",
  "Apa yang paling kamu harapkan dari hubungan ini?",
  "Hal apa yang paling kamu takut kehilangan?",
  "Apa pelajaran paling berat yang pernah kamu dapat?",
  "Bagaimana kamu ingin dicintai?",
  "Hal apa yang sulit kamu percayai dari orang lain?",
  "Apa yang membuat kamu merasa gagal?",
  "Menurut kamu, cinta bisa bertahan karena apa?",
  "Apa hal yang paling kamu sesali?",
  "Apa kebutuhan emosional kamu yang sering tidak terpenuhi?",
  "Bagaimana cara kamu menunjukkan cinta?",
  "Apa arti kesetiaan buat kamu?",
  "Apa yang membuat kamu tetap bertahan saat keadaan sulit?",
  "Hal apa yang paling kamu khawatirkan tentang dirimu sendiri?",
  "Apa arti kejujuran dalam hubungan menurut kamu?",
  "Apa yang membuat kamu merasa dihargai?",
  "Apa peran komunikasi dalam hubungan bagi kamu?",
  "Hal apa yang bikin kamu sulit membuka diri?",
  "Apa hal terpenting yang ingin kamu capai dalam hidup?",
  "Bagaimana kamu memaknai kehilangan?",
  "Apa yang kamu pelajari dari hubungan masa lalu?",
  "Hal apa yang membuat kamu takut berharap?",
  "Bagaimana kamu ingin dikenang oleh orang terdekat?",
  "Apa arti tumbuh bersama dalam hubungan?",
  "Hal apa yang paling kamu butuhkan dari aku saat ini?",
  "Menurut kamu, apa makna cinta jangka panjang?",
  "Apa yang paling kamu perjuangkan dalam hidup?",
  "Hal apa yang paling sulit kamu terima tentang dirimu?",
  "Apa arti kepercayaan buat kamu?",
  "Kapan terakhir kali kamu merasa dikecewakan?",
  "Apa yang bikin kamu merasa tidak aman?",
  "Apa ketakutan terbesar kamu dalam mencintai?",
  "Bagaimana kamu menghadapi rasa kehilangan?",
  "Apa yang kamu butuhkan agar bisa merasa tenang?",
  "Apa arti kesepian buat kamu?",
  "Apa hal yang ingin kamu ubah dari dirimu?",
  "Bagaimana cara kamu menyembuhkan diri saat terluka?",
  "Apa yang membuat kamu merasa cukup?",
  "Apa arti keberanian buat kamu?",
  "Apa yang paling kamu hargai dari dirimu sendiri?",
  "Apa hal yang paling sulit kamu lepaskan?",
  "Apa arti dicintai tanpa syarat menurut kamu?",
  "Apa yang membuat kamu tetap bertahan dalam hubungan?",
  "Apa ketakutan terdalam kamu yang jarang kamu ceritakan?",
  "Bagaimana kamu melihat dirimu 5 tahun ke depan?",
  "Apa yang paling kamu harapkan dari pasangan hidup?",
  "Apa arti saling memahami bagi kamu?",
  "Apa luka lama yang masih sering muncul?",
  "Apa yang bikin kamu merasa sendirian?",
  "Apa arti tumbuh sebagai individu dalam hubungan?",
  "Apa yang kamu butuhkan untuk merasa aman mencintai?",
  "Apa arti menerima kekurangan pasangan?",
  "Apa yang bikin kamu takut untuk berubah?",
  "Bagaimana kamu ingin dicintai saat kamu lemah?",
  "Apa yang paling kamu jaga dalam hubungan?",
  "Apa arti kehadiran seseorang dalam hidup kamu?",
  "Apa yang bikin kamu percaya pada cinta?",
  "Apa ketakutan terbesar kamu tentang kehilangan aku?",
  "Apa arti menjadi pasangan yang baik menurut kamu?",
  "Apa yang paling kamu harapkan dari masa depan bersama?",
  "Apa arti cinta yang dewasa menurut kamu?",
  "Apa yang bikin kamu yakin untuk bertahan?",
  "Apa arti saling bertumbuh dalam hubungan?",
  "Apa bagian dari dirimu yang paling jarang orang pahami?",
  "Apa yang paling kamu takutkan jika hubungan ini berakhir?",
  "Apa arti merasa aman dengan seseorang bagi kamu?",
  "Bagaimana cara kamu menghadapi rasa kecewa terhadap diri sendiri?",
  "Apa luka yang paling lama kamu sembuhkan?",
  "Apa yang membuat kamu sulit meminta bantuan?",
  "Apa yang kamu harapkan dari aku saat kamu sedang rapuh?",
  "Apa arti dicintai apa adanya menurut kamu?",
  "Apa yang paling kamu pelajari dari rasa kehilangan?",
  "Apa hal yang paling kamu butuhkan agar bisa bertahan?",
  "Apa yang membuat kamu merasa tidak sendirian?",
  "Apa arti menerima diri sendiri bagi kamu?",
  "Apa yang paling kamu takutkan tentang masa depan hubungan ini?",
];
