export const CasualQuestions: string[] = [
  "Kalau hari ini bebas seharian, kamu mau ngapain?",
  "Minuman favorit kamu kalau lagi capek?",
  "Lebih pilih pantai atau gunung?",
  "Lagu apa yang sering kamu putar akhir-akhir ini?",
  "Kalau bisa langsung liburan sekarang, mau ke mana?",
  "Film yang paling sering kamu tonton ulang?",
  "Kebiasaan kecil kamu yang orang jarang tahu?",
  "Sarapan favorit kamu?",
  "Kalau lagi bad mood, biasanya kamu ngapain?",
  "Lebih suka chat atau telepon?",
  "Makanan yang selalu bikin kamu bahagia?",
  "Tempat nongkrong favorit kamu?",
  "Kalau hujan deras, kamu lebih suka di rumah atau keluar?",
  "Hobi yang pengen kamu tekuni tapi belum kesampaian?",
  "Aplikasi yang paling sering kamu buka?",
  "Hal random yang bikin kamu ketawa?",
  "Kamu tipe bangun pagi atau begadang?",
  "Kalau nonton film, lebih suka sendiri atau bareng?",
  "Cemilan favorit pas malam hari?",
  "Musik galau atau musik semangat?",
  "Hal kecil yang bikin hari kamu jadi lebih baik?",
  "Kalau weekend ideal menurut kamu seperti apa?",
  "Mending kopi atau teh?",
  "Kebiasaan aneh tapi nyaman buat kamu?",
  "Kalau lagi capek kerja, hal pertama yang kamu cari apa?",
  "Lebih suka suasana ramai atau sepi?",
  "Kalau masak, menu paling jago apa?",
  "Emoji yang paling sering kamu pakai?",
  "Kalau punya hewan peliharaan, pengennya apa?",
  "Cuaca favorit kamu?",
  "Kalau lagi nunggu sesuatu, biasanya ngapain?",
  "Hal sederhana yang sering kamu syukuri?",
  "Kalau disuruh describe diri kamu dengan 3 kata?",
  "Lebih suka nonton series atau film?",
  "Momen kecil yang sering kamu rindukan?",
  "Kalau lagi bete, kamu pengen ditemani atau sendiri?",
  "Makanan yang nggak pernah bosen kamu makan?",
  "Kalau libur panjang, lebih pilih istirahat atau jalan?",
  "Hal random yang bikin kamu langsung ingat aku?",
  "Waktu favorit dalam sehari?",
  "Kalau disuruh tukar pekerjaan sehari, mau jadi apa?",
  "Game atau permainan favorit kamu?",
  "Lebih suka foto atau video?",
  "Hal kecil yang bikin kamu merasa tenang?",
  "Kalau malam nggak bisa tidur, biasanya ngapain?",
  "Kalau mood lagi bagus, kelihatan dari apa?",
  "Makanan manis atau asin?",
  "Tempat yang bikin kamu merasa aman?",
  "Hal kecil yang sering bikin kamu tersenyum sendiri?",
  "Kalau lagi kangen seseorang, biasanya kamu ngapain?",
  "Kalau disuruh pilih satu lagu buat hari ini, lagu apa?",
  "Hal paling random yang kamu lakukan minggu ini?",
  "Kalau lagi sendirian di rumah, ngapain biasanya?",
  "Hal kecil yang bikin kamu ilfeel?",
  "Kalau nonton YouTube, topik favorit kamu apa?",
  "Lebih suka jalan pagi atau malam?",
  "Kalau lagi capek, pengen ditemani atau didiemin?",
  "Makanan favorit waktu kecil?",
  "Kalau disuruh liburan dadakan, siap nggak?",
  "Hal kecil yang bikin kamu merasa produktif?",
  "Kalau lagi bete, kamu lebih suka ngomel atau diam?",
  "Minuman yang paling sering kamu beli?",
  "Kalau hujan, kamu tipe rebahan atau tidur?",
  "Hal random yang sering kamu pikirin?",
  "Lebih suka kado atau quality time?",
  "Kalau lagi seneng, biasanya kamu ngapain?",
  "Hal kecil yang bikin kamu merasa lucu sendiri?",
  "Kalau disuruh masak buat aku, kamu masak apa?",
  "Hal sederhana yang bikin kamu merasa dicari?",
  "Kalau lagi kosong pikiran, kamu mikir apa?",
  "Lebih suka suasana cafe atau rumah?",
  "Kalau lagi capek mental, kamu ngapain?",
  "Hal kecil yang bikin kamu nyaman sama seseorang?",
  "Kalau lagi males, cara kamu balikin mood gimana?",
  "Momen kecil yang bikin kamu merasa hidup?",
  "Kalau lagi diem lama, kamu mikir apa?",
  "Hal kecil yang bikin kamu merasa diperhatiin?",
  "Kalau disuruh jujur, kamu tipe posesif nggak?",
  "Hal random yang bikin kamu ketawa sendiri di HP?",
  "Kalau lagi nunggu balasan chat, ngapain biasanya?",
  "Hal kecil yang bikin kamu senyum tanpa sadar?",
  "Kalau disuruh pilih satu hal buat diulang, apa?",
  "Kalau hari ini mood kamu warna, warnanya apa?",
  "Hal kecil yang bikin kamu merasa diterima?",
  "Kalau lagi santai, kamu lebih suka ngapain?",
  "Kalau lagi hujan dan dingin, makanan apa yang paling kamu cari?",
  "Hal kecil apa yang bikin kamu langsung bad mood?",
  "Kalau disuruh libur tanpa HP sehari, sanggup nggak?",
  "Minuman favorit kamu kalau lagi panas banget?",
  "Kalau lagi capek banget, kamu lebih pilih tidur atau scroll HP?",
  "Hal sepele apa yang bikin kamu ngerasa diperhatiin?",
  "Kalau lagi diem, kamu beneran kosong atau banyak mikir?",
  "Kalau disuruh pilih: pagi cerah atau malam tenang?",
  "Makanan yang kamu suka tapi orang lain sering nggak suka?",
  "Kalau lagi seneng, kamu tipe cerita atau simpan sendiri?",
  "Hal kecil apa yang bikin kamu betah di satu tempat?",
  "Kalau lagi males ngomong, biasanya kenapa?",
  "Kegiatan santai favorit kamu tanpa gadget?",
  "Kalau lagi jenuh, kamu pengen diajak ngapain?",
  "Hal sederhana yang bikin kamu ngerasa ditemani?",
];

export const DeepQuestions: string[] = [
  "Apa arti hubungan yang sehat menurut kamu?",
  "Hal apa yang paling kamu takuti dalam hubungan?",
  "Apa luka emosional yang masih kamu bawa sampai sekarang?",
  "Menurut kamu, cinta itu pilihan atau perasaan?",
  "Hal apa yang paling sulit kamu ungkapkan ke orang lain?",
  "Kapan terakhir kali kamu merasa sangat rapuh?",
  "Apa yang membuat kamu merasa benar-benar dicintai?",
  "Menurut kamu, apa tanggung jawab terbesar dalam hubungan?",
  "Hal apa yang paling kamu hargai dari pasangan?",
  "Apa batasan yang penting buat kamu dalam hubungan?",
  "Apa ketakutan terbesar kamu tentang masa depan?",
  "Kapan kamu merasa paling bangga pada diri sendiri?",
  "Apa definisi bahagia versi kamu?",
  "Hal apa yang paling sulit kamu maafkan?",
  "Apa yang biasanya kamu pendam sendiri?",
  "Menurut kamu, apa arti komitmen?",
  "Hal apa yang bisa membuat kamu menjauh dari seseorang?",
  "Apa yang paling kamu butuhkan saat sedang down?",
  "Bagaimana cara kamu menghadapi konflik?",
  "Apa pengalaman hidup yang paling membentuk kamu?",
  "Apa mimpi terbesar kamu yang jarang kamu ceritakan?",
  "Hal apa yang bikin kamu merasa tidak cukup?",
  "Menurut kamu, pasangan ideal itu seperti apa?",
  "Apa arti rumah bagi kamu?",
  "Hal apa yang bikin kamu merasa aman secara emosional?",
  "Apa yang paling kamu harapkan dari hubungan ini?",
  "Hal apa yang paling kamu takut kehilangan?",
  "Apa pelajaran paling berat yang pernah kamu dapat?",
  "Bagaimana kamu ingin dicintai?",
  "Hal apa yang sulit kamu percayai dari orang lain?",
  "Apa yang membuat kamu merasa gagal?",
  "Menurut kamu, cinta bisa bertahan karena apa?",
  "Apa hal yang paling kamu sesali?",
  "Apa kebutuhan emosional kamu yang sering tidak terpenuhi?",
  "Bagaimana cara kamu menunjukkan cinta?",
  "Apa arti kesetiaan buat kamu?",
  "Apa yang membuat kamu tetap bertahan saat keadaan sulit?",
  "Hal apa yang paling kamu khawatirkan tentang dirimu sendiri?",
  "Apa arti kejujuran dalam hubungan menurut kamu?",
  "Apa yang membuat kamu merasa dihargai?",
  "Apa peran komunikasi dalam hubungan bagi kamu?",
  "Hal apa yang bikin kamu sulit membuka diri?",
  "Apa hal terpenting yang ingin kamu capai dalam hidup?",
  "Bagaimana kamu memaknai kehilangan?",
  "Apa yang kamu pelajari dari hubungan masa lalu?",
  "Hal apa yang membuat kamu takut berharap?",
  "Bagaimana kamu ingin dikenang oleh orang terdekat?",
  "Apa arti tumbuh bersama dalam hubungan?",
  "Hal apa yang paling kamu butuhkan dari aku saat ini?",
  "Menurut kamu, apa makna cinta jangka panjang?",
  "Apa yang paling kamu perjuangkan dalam hidup?",
  "Hal apa yang paling sulit kamu terima tentang dirimu?",
  "Apa arti kepercayaan buat kamu?",
  "Kapan terakhir kali kamu merasa dikecewakan?",
  "Apa yang bikin kamu merasa tidak aman?",
  "Apa ketakutan terbesar kamu dalam mencintai?",
  "Bagaimana kamu menghadapi rasa kehilangan?",
  "Apa yang kamu butuhkan agar bisa merasa tenang?",
  "Apa arti kesepian buat kamu?",
  "Apa hal yang ingin kamu ubah dari dirimu?",
  "Bagaimana cara kamu menyembuhkan diri saat terluka?",
  "Apa yang membuat kamu merasa cukup?",
  "Apa arti keberanian buat kamu?",
  "Apa yang paling kamu hargai dari dirimu sendiri?",
  "Apa hal yang paling sulit kamu lepaskan?",
  "Apa arti dicintai tanpa syarat menurut kamu?",
  "Apa yang membuat kamu tetap bertahan dalam hubungan?",
  "Apa ketakutan terdalam kamu yang jarang kamu ceritakan?",
  "Bagaimana kamu melihat dirimu 5 tahun ke depan?",
  "Apa yang paling kamu harapkan dari pasangan hidup?",
  "Apa arti saling memahami bagi kamu?",
  "Apa luka lama yang masih sering muncul?",
  "Apa yang bikin kamu merasa sendirian?",
  "Apa arti tumbuh sebagai individu dalam hubungan?",
  "Apa yang kamu butuhkan untuk merasa aman mencintai?",
  "Apa arti menerima kekurangan pasangan?",
  "Apa yang bikin kamu takut untuk berubah?",
  "Bagaimana kamu ingin dicintai saat kamu lemah?",
  "Apa yang paling kamu jaga dalam hubungan?",
  "Apa arti kehadiran seseorang dalam hidup kamu?",
  "Apa yang bikin kamu percaya pada cinta?",
  "Apa ketakutan terbesar kamu tentang kehilangan aku?",
  "Apa arti menjadi pasangan yang baik menurut kamu?",
  "Apa yang paling kamu harapkan dari masa depan bersama?",
  "Apa arti cinta yang dewasa menurut kamu?",
  "Apa yang bikin kamu yakin untuk bertahan?",
  "Apa arti saling bertumbuh dalam hubungan?",
  "Apa bagian dari dirimu yang paling jarang orang pahami?",
  "Apa yang paling kamu takutkan jika hubungan ini berakhir?",
  "Apa arti merasa aman dengan seseorang bagi kamu?",
  "Bagaimana cara kamu menghadapi rasa kecewa terhadap diri sendiri?",
  "Apa luka yang paling lama kamu sembuhkan?",
  "Apa yang membuat kamu sulit meminta bantuan?",
  "Apa yang kamu harapkan dari aku saat kamu sedang rapuh?",
  "Apa arti dicintai apa adanya menurut kamu?",
  "Apa yang paling kamu pelajari dari rasa kehilangan?",
  "Apa hal yang paling kamu butuhkan agar bisa bertahan?",
  "Apa yang membuat kamu merasa tidak sendirian?",
  "Apa arti menerima diri sendiri bagi kamu?",
  "Apa yang paling kamu takutkan tentang masa depan hubungan ini?",
];

export const FriendshipCasualQuestions: string[] = [
  "Kalau lagi kumpul lama, kamu tipe betah atau pengen pulang?",
  "Hal kecil apa yang bikin nongkrong jadi lebih seru?",
  "Kalau temen kamu ngajak spontan, kamu tipe ikut atau mikir dulu?",
  "Siapa yang paling sering ngasih ide random?",
  "Kalau lagi rame, kamu tipe aktif atau pengamat?",
  "Hal kecil yang bikin kamu merasa nyatu sama circle?",
  "Kalau lagi nongkrong, kamu tipe makan terus atau ngobrol terus?",
  "Siapa yang paling sering jadi penenang suasana?",
  "Kalau temen kamu tiba-tiba diem, kamu biasanya sadar nggak?",
  "Hal kecil yang bikin kamu betah berjam-jam bareng temen?",
  "Kalau lagi capek, nongkrong bantu atau malah capek?",
  "Siapa yang paling sering bikin keputusan dadakan?",
  "Kalau lagi rame, kamu tipe fokus ngobrol atau sambil HP-an?",
  "Hal kecil yang bikin kamu merasa satu frekuensi?",
  "Kalau disuruh pilih, kumpul rame atau ngobrol berdua?",
  "Hal sederhana yang bikin pertemanan terasa ringan?",
  "Hal paling random yang pernah kita lakukan bareng?",
  "Kalau lagi nongkrong, kamu paling sering ngapain?",
  "Makanan favorit kalau lagi bareng temen?",
  "Siapa yang paling sering telat di circle kamu?",
  "Kalau liburan bareng temen, kamu tipe ribet atau santai?",
  "Hal receh yang selalu bikin ketawa bareng?",
  "Kalau lagi capek, lebih milih curhat atau bercanda?",
  "Siapa temen yang paling sering kamu chat?",
  "Kegiatan favorit bareng temen selain nongkrong?",
  "Kalau lagi rame-rame, kamu tipe dominan atau ngikut?",
  "Hal kecil yang bikin kamu betah sama temen?",
  "Kalau main game bareng, kamu tipe serius atau fun?",
  "Kalau lagi lapar bareng, siapa yang paling heboh?",
  "Kalau disuruh describe circle kamu, 3 kata apa?",
  "Temen kamu tipe ribut atau kalem?",
  "Kalau lagi kumpul, topik apa yang paling sering dibahas?",
  "Hal lucu yang cuma dimengerti circle kamu?",
  "Kalau temen kamu ngajak dadakan, kamu biasanya gimana?",
  "Momen paling ngakak bareng temen?",
  "Kalau lagi jalan, kamu tipe foto-foto atau nikmatin?",
  "Siapa yang paling sering jadi bahan bercandaan?",
  "Hal kecil yang bikin suasana jadi rame?",
  "Kalau temen kamu curhat, kamu tipe pendengar atau penasehat?",
  "Siapa yang paling sering ngajak nongkrong duluan?",
  "Kalau lagi diem di tongkrongan, kamu mikir apa?",
  "Kegiatan random yang sering dilakukan bareng?",
  "Kalau hujan pas nongkrong, biasanya ngapain?",
  "Temen kamu tipe spontan atau terencana?",
  "Kalau lagi kumpul lama, kamu cepat capek atau betah?",
  "Hal kecil yang bikin kamu merasa satu frekuensi sama temen?",
  "Kalau disuruh pilih, nongkrong siang atau malam?",
  "Kalau lagi rame, kamu lebih banyak ngomong atau dengerin?",
  "Siapa yang paling sering bikin suasana awkward?",
  "Kalau main bareng, kamu lebih suka indoor atau outdoor?",
  "Hal receh yang selalu diulang tapi tetap lucu?",
  "Kalau temen kamu ngilang lama, reaksi kamu gimana?",
  "Siapa yang paling sering ngide random?",
  "Kalau lagi capek mental, nongkrong bantu nggak?",
  "Kalau lagi kumpul, kamu tipe ngemil atau ngobrol?",
  "Hal kecil yang bikin kamu merasa diterima di circle?",
  "Kalau disuruh pilih satu momen buat diulang bareng temen?",
  "Siapa yang paling sering jadi penenang?",
  "Kalau lagi diem, temen kamu peka atau cuek?",
  "Hal kecil yang bikin kamu kangen nongkrong?",
  "Kalau temen kamu berubah, kamu sadar dari apa?",
  "Kalau lagi kumpul, kamu tipe main HP atau fokus ngobrol?",
  "Hal sederhana yang bikin pertemanan terasa hangat?",
  "Kalau temen kamu sukses, reaksi pertama kamu?",
  "Siapa yang paling sering ngelawak?",
  "Kalau lagi bete, temen kamu ngaruh nggak ke mood?",
  "Hal kecil yang bikin kamu merasa nyambung?",
  "Kalau lagi jalan jauh, kamu tipe ngobrol atau tidur?",
  "Siapa yang paling sering ngasih ide?",
  "Kalau lagi kumpul, kamu tipe aktif atau observer?",
  "Hal lucu yang cuma terjadi karena temen kamu?",
  "Kalau temen kamu sedih, kamu biasanya ngapain?",
  "Kalau disuruh pilih satu kebiasaan circle kamu?",
  "Hal kecil yang bikin kamu betah lama-lama?",
  "Kalau lagi rame, kamu gampang capek nggak?",
  "Siapa yang paling sering jadi penutup obrolan?",
  "Kalau temen kamu berubah drastis, kamu bakal nanya?",
  "Hal kecil yang bikin kamu ngerasa dihargai?",
  "Kalau lagi nongkrong lama, kamu butuh break nggak?",
  "Siapa yang paling sering ngingetin?",
  "Kalau temen kamu lagi capek, kamu sadar dari apa?",
  "Hal kecil yang bikin kamu merasa satu tim?",
  "Kalau lagi rame, kamu tipe menikmati atau kewalahan?",
  "Siapa yang paling sering ngatur jadwal?",
  "Kalau temen kamu tiba-tiba diem, reaksi kamu?",
  "Hal sederhana yang bikin pertemanan awet?",
  "Kalau lagi kumpul, kamu tipe ngikut atau ngarahin?",
  "Siapa yang paling sering bikin suasana cair?",
  "Kalau temen kamu lagi seneng, kamu ikut kebawa nggak?",
  "Hal kecil yang bikin kamu nyaman di circle?",
  "Kalau disuruh describe temen kamu satu kata?",
  "Kalau lagi rame, kamu tipe stay atau cabut duluan?",
  "Siapa yang paling sering jadi penengah?",
  "Kalau temen kamu salah, kamu tipe negur atau diem?",
  "Hal kecil yang bikin kamu merasa dianggap?",
  "Kalau lagi nongkrong, kamu tipe lama atau sebentar?",
  "Siapa yang paling sering ngajak ngobrol serius?",
  "Hal kecil yang bikin kamu pengen jaga pertemanan?",
  "Kalau temen kamu ngajak ngobrol tengah malam, reaksi kamu?",
  "Hal sederhana yang bikin kamu merasa dekat?",
];

export const FriendshipDeepQuestions: string[] = [
  "Apa bagian dari dirimu yang jarang kamu tunjukkan ke teman?",
  "Apa yang paling kamu takutkan jika kehilangan sahabat?",
  "Apa arti merasa aman secara emosional dengan teman?",
  "Bagaimana cara kamu menghadapi kekecewaan pada teman dekat?",
  "Apa luka pertemanan yang paling sulit kamu lepaskan?",
  "Apa yang membuat kamu sulit berkata jujur pada teman?",
  "Apa yang kamu harapkan dari teman saat kamu sedang rapuh?",
  "Apa arti diterima apa adanya dalam pertemanan?",
  "Apa yang paling kamu pelajari dari pertemanan yang berakhir?",
  "Apa yang bikin kamu bertahan meski pertemanan terasa berat?",
  "Apa arti menjadi tempat pulang bagi seorang teman?",
  "Apa yang membuat kamu merasa cukup dalam pertemanan?",
  "Apa arti pertemanan yang layak diperjuangkan menurut kamu?",
  "Apa arti pertemanan yang sehat menurut kamu?",
  "Hal apa yang paling kamu hargai dari seorang teman?",
  "Kapan kamu merasa benar-benar diterima sebagai teman?",
  "Apa luka pertemanan yang masih kamu ingat?",
  "Hal apa yang paling kamu takutkan dalam pertemanan?",
  "Apa arti loyalitas dalam pertemanan?",
  "Kapan terakhir kali kamu kecewa dengan teman?",
  "Bagaimana kamu menghadapi konflik dengan teman?",
  "Apa batasan penting dalam pertemanan menurut kamu?",
  "Apa yang bikin kamu bertahan dalam sebuah pertemanan?",
  "Hal apa yang bikin kamu menjauh dari seorang teman?",
  "Apa arti kejujuran dalam pertemanan?",
  "Kapan kamu merasa pertemanan terasa berat?",
  "Apa pelajaran terbesar dari pertemanan masa lalu?",
  "Apa arti dipercaya oleh seorang teman?",
  "Bagaimana kamu menunjukkan kepedulian ke teman?",
  "Apa yang kamu butuhkan dari teman saat kamu sedang down?",
  "Hal apa yang paling sulit kamu terima dari teman?",
  "Apa arti saling mendukung dalam pertemanan?",
  "Kapan kamu merasa sendirian meski punya teman?",
  "Apa peran komunikasi dalam pertemanan menurut kamu?",
  "Apa yang bikin kamu merasa tidak dihargai sebagai teman?",
  "Bagaimana kamu memaknai kehilangan teman?",
  "Apa arti pertemanan jangka panjang buat kamu?",
  "Hal apa yang bikin kamu merasa aman dalam pertemanan?",
  "Apa yang kamu harapkan dari seorang sahabat?",
  "Bagaimana kamu menghadapi perubahan dalam pertemanan?",
  "Apa arti menjadi teman yang baik menurut kamu?",
  "Hal apa yang paling kamu jaga dalam pertemanan?",
  "Apa yang bikin kamu merasa cukup sebagai teman?",
  "Apa arti menerima kekurangan teman?",
  "Kapan kamu merasa pertemanan terasa sepihak?",
  "Apa arti hadir untuk teman menurut kamu?",
  "Apa luka lama dari pertemanan yang masih terasa?",
  "Bagaimana kamu menyelesaikan masalah dengan teman?",
  "Apa yang bikin kamu sulit percaya pada teman?",
  "Apa arti saling memahami dalam pertemanan?",
  "Kapan kamu merasa bangga dengan seorang teman?",
  "Apa arti mendukung mimpi teman?",
  "Apa yang bikin kamu merasa ditinggalkan dalam pertemanan?",
  "Bagaimana kamu menghadapi rasa cemburu dalam pertemanan?",
  "Apa arti batasan sehat dalam pertemanan?",
  "Apa yang bikin kamu merasa dibutuhkan sebagai teman?",
  "Kapan kamu merasa pertemanan memberi energi?",
  "Apa arti teman dalam fase hidup kamu sekarang?",
  "Apa yang paling kamu pelajari dari konflik pertemanan?",
  "Apa arti tumbuh bersama dalam pertemanan?",
  "Apa yang bikin kamu takut membuka diri ke teman?",
  "Apa arti kehadiran teman saat kamu gagal?",
  "Kapan kamu merasa pertemanan perlu diperjuangkan?",
  "Apa arti saling menghargai dalam pertemanan?",
  "Apa yang bikin kamu merasa dikhianati?",
  "Bagaimana kamu memaafkan teman yang menyakiti?",
  "Apa arti pertemanan tanpa syarat menurut kamu?",
  "Apa yang kamu butuhkan agar pertemanan terasa seimbang?",
  "Apa arti mendengarkan dalam pertemanan?",
  "Apa yang bikin kamu merasa pertemanan berubah?",
  "Bagaimana kamu menjaga pertemanan tetap sehat?",
  "Apa arti saling jujur meski menyakitkan?",
  "Apa yang bikin kamu takut kehilangan teman?",
  "Apa arti kepercayaan dalam pertemanan?",
  "Apa yang kamu lakukan saat pertemanan terasa menjauh?",
  "Apa arti menerima perbedaan dalam pertemanan?",
  "Kapan kamu merasa pertemanan menguatkan kamu?",
  "Apa arti teman sejati menurut kamu?",
  "Apa yang bikin kamu merasa diabaikan?",
  "Bagaimana kamu ingin diperlakukan sebagai teman?",
  "Apa arti hadir tanpa diminta?",
  "Apa yang bikin kamu tetap bertahan meski kecewa?",
  "Apa arti berbagi beban dalam pertemanan?",
  "Kapan kamu merasa pertemanan terasa tulus?",
  "Apa yang bikin kamu merasa cukup didengar?",
  "Apa arti tumbuh sebagai individu dalam pertemanan?",
  "Apa yang bikin kamu ragu melanjutkan pertemanan?",
  "Apa arti dukungan emosional dari teman?",
  "Apa yang kamu butuhkan agar pertemanan terasa aman?",
  "Apa arti kehadiran diam dalam pertemanan?",
  "Apa yang bikin kamu percaya pada ketulusan teman?",
  "Apa arti pertemanan di saat sulit?",
  "Apa yang bikin kamu merasa pertemanan layak dijaga?",
  "Apa arti menjadi tempat pulang bagi teman?",
  "Apa yang kamu harapkan dari pertemanan di masa depan?",
  "Apa arti pertemanan yang dewasa menurut kamu?",
  "Apa yang bikin kamu yakin pada sebuah pertemanan?",
  "Apa arti saling bertumbuh sebagai teman?",
  "Apa yang paling kamu hargai dari pertemanan ini?",
  "Apa arti kehadiran teman dalam hidup kamu?",
];

